name: Merge Sketch documents using Fusion

on:
  push:
    paths:
      - ./**.sketch
      - .github/workflows/**.yml
    branches: [main]
  pull_request:
    paths:
      - ./**.sketch
      - .github/workflows/**.yml
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Run Sketch Fusion
        run: npm start
      # - name: Push changes in output file to repo
      #   uses: actions-x/commit@v2
      #   with:
      #     email: developer@sketch.com
      #     name: Sketch Developer
      #     files: output.sketch
